#!/bin/bash

# CLI Script for iRedMail 
# ------------------------------------------------------------------------
# Author:    Peter-Christoph Haider
# ------------------------------------------------------------------------

SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")

# resolve symlinks
while [ -h $SELF_PATH ]; do
    DIR=$(dirname -- "$SELF_PATH")
    SYM=$(readlink $SELF_PATH)
    SELF_PATH=$(cd $DIR && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
done

DIR=$(dirname "$SELF_PATH")

# Path to the PHP command
CMD_PHP="php"


# ====================== INIT APPLICATION PARAMS =========================

XARGS=""
while [ "$1" != "" ]; do
	case $1 in
		* )
			XARGS="$XARGS $1"
		;;
	esac
	shift
done

$CMD_PHP "$DIR/cli.php" $XARGS
exit 0
